title = "Newton Ni"
description = "Newton Ni's personal website."
base_url = "https://nwtnni.me"
author = "Newton Ni"

compile_sass = true
feed_filenames = ["atom.xml", "rss.xml"]
generate_feeds = true
hard_link_static = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-light"
